version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosq-poc
    ports:
      - "1883:1883"    # MQTT
      - "9001:9001"    # Websockets Í
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
